<a href="https://colab.research.google.com/github/Fentahun60/Fentahun/blob/main/access.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [166]:
import pandas as pd

# Assuming the file is a Stata file (.dta)
df = pd.read_stata('/content/drive/MyDrive/selected_var_all.dta')

# Display the head of the DataFrame
display(df.head())

,Country,v001,v005,v007,Maternal_age,highest_educational_level,Residence,sex_of_hh,v157,v158,...,currently_pregnant,History_abortion,contraceptive_use_and_intention,visited_HF_last_12months,v467b,v467c,v467d,v467f,covered_by_health_insurance,Working_status
0,AO7,1,1086089,2016,38,no education,rural,male,not at all,not at all,...,no or unsure,yes,does not intend to use,no,not a big problem,big problem,big problem,not a big problem,no,yes
1,AO7,1,1086089,2016,40,no education,rural,male,not at all,not at all,...,yes,no,does not intend to use,no,not a big problem,not a big problem,not a big problem,not a big problem,no,yes
2,AO7,1,1086089,2016,16,no education,rural,male,not at all,not at all,...,yes,no,does not intend to use,yes,big problem,big problem,not a big problem,not a big problem,no,yes
3,AO7,1,1086089,2016,43,primary,rural,male,not at all,not at all,...,no or unsure,yes,does not intend to use,no,big problem,big problem,not a big problem,not a big problem,no,yes
4,AO7,1,1086089,2016,25,no education,rural,male,not at all,not at all,...,no or unsure,no,does not intend to use,no,not a big problem,not a big problem,not a big problem,not a big problem,no,yes

In [167]:
df.shape

(473294, 25)

In [168]:
# Create a cross-tabulation of 'Country' and 'v007'
cross_tab = pd.crosstab(df['Country'], df['v007'])

# Display the cross-tabulation
display(cross_tab)

v007,2008,2012,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
Country,,,,,,,,,,,,
AO7,0,0,7266,7113,0,0,0,0,0,0,0,0
BF8,0,0,0,0,0,0,0,0,17659,0,0,0
BJ7,0,0,0,0,7387,8541,0,0,0,0,0,0
BU7,0,0,0,10012,7257,0,0,0,0,0,0,0
CD8,0,0,0,0,0,0,0,0,0,0,21684,5899
CI8,0,0,0,0,0,0,0,0,14877,0,0,0
CM7,0,0,0,0,0,14590,87,0,0,0,0,0
ET7,15683,0,0,0,0,0,0,0,0,0,0,0
GA7,0,0,0,0,0,0,911,4695,5437,0,0,0
GH8,0,0,0,0,0,0,0,0,0,13134,1880,0
GM7,0,0,0,0,0,0,2589,9276,0,0,0,0
GN7,0,0,0,0,0,10874,0,0,0,0,0,0
KE8,0,0,0,0,0,0,0,0,0,32156,0,0
KM6,0,5329,0,0,0,0,0,0,0,0,0,0
LB7,0,0,0,0,0,0,4529,3536,0,0,0,0
LS8,0,0,0,0,0,0,0,0,0,0,1844,4569
MD7,0,0,0,0,0,0,0,0,18869,0,0,0
ML8,0,0,0,0,0,0,0,0,0,0,5535,14819
MR7,0,0,0,0,0,0,3869,9407,2438,0,0,0
MW7,0,0,16606,7956,0,0,0,0,0,0,0,0
MZ8,0,0,0,0,0,0,0,0,0,11084,2099,0
NG8,0,0,0,0,0,0,0,0,0,0,4992,34058
RW7,0,0,0,0,0,0,3782,10852,0,0,0,0
SL7,0,0,0,0,0,0,15574,0,0,0,0,0
SN8,0,0,0,0,0,0,0,0,0,0,16583,0
TZ8,0,0,0,0,0,0,0,0,0,15254,0,0
UG7,0,0,0,18506,0,0,0,0,0,0,0,0
ZA7,0,0,0,8514,0,0,0,0,0,0,0,0
ZM7,0,0,0,0,0,13327,356,0,0,0,0,0

In [169]:
df.shape

(473294, 25)

In [170]:
# Delete all rows if the country is KM6
df = df[df['Country'] != 'KM6']

# Display the shape of the updated DataFrame to confirm the rows were removed
display(df.shape)

(467965, 25)

In [171]:
# Check for missing values in each column
missing_values = df.isnull().sum()

# Display the number of missing values for each column
display(missing_values)

Country                                0
v001                                   0
v005                                   0
v007                                   0
Maternal_age                           0
highest_educational_level              0
Residence                              0
sex_of_hh                              0
v157                                   8
v158                                   0
v159                                   0
owns_mobile_telephone                  0
use_of_internet                        0
Wealth_index                           0
gave_birth_in_the_5yrs              5838
currently_pregnant                  5838
History_abortion                    5838
contraceptive_use_and_intention     5838
visited_HF_last_12months           27047
v467b                              27010
v467c                              27010
v467d                              27010
v467f                              27010
covered_by_health_insurance        43911
Working_status                      4688
dtype: int64

In [172]:
# Create a frequency table for 'v467b'
v467b_counts = df['v467b'].value_counts()

# Display the frequency table
display(v467b_counts)

v467b
not a big problem    355219
big problem           85736
9.0                       0
Name: count, dtype: int64

In [173]:
# Create a frequency table for 'v467b'
v467b_counts = df['v467c'].value_counts()

# Display the frequency table
display(v467b_counts)

v467c
big problem          231121
not a big problem    209834
9.0                       0
Name: count, dtype: int64

In [174]:
# Create a frequency table for 'v467b'
v467d_counts = df['v467d'].value_counts()

# Display the frequency table
display(v467d_counts)

v467d
not a big problem    280193
big problem          160762
9.0                       0
Name: count, dtype: int64

In [175]:
# Create a frequency table for 'v467b'
v467f_counts = df['v467f'].value_counts()

# Display the frequency table
display(v467f_counts)

v467f
not a big problem    340170
big problem          100785
9.0                       0
Name: count, dtype: int64

In [176]:
# Calculate the percentage of missing values for the specified columns
missing_percentage_v467b = (df['v467b'].isnull().sum() / len(df)) * 100
missing_percentage_v467c = (df['v467c'].isnull().sum() / len(df)) * 100
missing_percentage_v467d = (df['v467d'].isnull().sum() / len(df)) * 100
missing_percentage_v467f = (df['v467f'].isnull().sum() / len(df)) * 100

# Display the percentage of missing values
print(f"Percentage of missing values in 'v467b': {missing_percentage_v467b:.2f}%")
print(f"Percentage of missing values in 'v467c': {missing_percentage_v467c:.2f}%")
print(f"Percentage of missing values in 'v467d': {missing_percentage_v467d:.2f}%")
print(f"Percentage of missing values in 'v467f': {missing_percentage_v467f:.2f}%")

Percentage of missing values in 'v467b': 5.77%
Percentage of missing values in 'v467c': 5.77%
Percentage of missing values in 'v467d': 5.77%
Percentage of missing values in 'v467f': 5.77%

In [177]:
# Group by 'Country' and calculate the number of missing values for the specified columns
missing_values_by_country = df.groupby('Country')[['v467b', 'v467c', 'v467d', 'v467f']].apply(lambda x: x.isnull().sum())

# Calculate the total number of rows for each country
total_rows_by_country = df.groupby('Country').size()

# Calculate the percentage of missing values by country
missing_percentage_by_country = missing_values_by_country.divide(total_rows_by_country, axis=0) * 100

# Display the number of missing values by country
print("Number of missing values by Country:")
display(missing_values_by_country)

# Display the percentage of missing values by country
print("\nPercentage of missing values by Country:")
display(missing_percentage_by_country)

Number of missing values by Country:

         v467b  v467c  v467d  v467f
Country
AO7          0      0      0      0
BF8          0      0      0      0
BJ7          0      0      0      0
BU7          0      0      0      0
CD8          0      0      0      0
CI8          0      0      0      0
CM7       1150   1150   1150   1150
ET7          0      0      0      0
GA7       3132   3132   3132   3132
GH8          0      0      0      0
GM7          0      0      0      0
GN7          0      0      0      0
KE8      15255  15255  15255  15255
LB7          0      0      0      0
LS8          0      0      0      0
MD7          0      0      0      0
ML8       3152   3152   3152   3152
MR7          0      0      0      0
MW7          0      0      0      0
MZ8          0      0      0      0
NG8          0      0      0      0
RW7          0      0      0      0
SL7          0      0      0      0
SN8          0      0      0      0
TZ8          0      0      0      0
UG7          0      0      0      0
ZA7       4321   4321   4321   4321
ZM7          0      0      0      0

Percentage of missing values by Country:

             v467b      v467c      v467d      v467f
Country
AO7       0.000000   0.000000   0.000000   0.000000
BF8       0.000000   0.000000   0.000000   0.000000
BJ7       0.000000   0.000000   0.000000   0.000000
BU7       0.000000   0.000000   0.000000   0.000000
CD8       0.000000   0.000000   0.000000   0.000000
CI8       0.000000   0.000000   0.000000   0.000000
CM7       7.835389   7.835389   7.835389   7.835389
ET7       0.000000   0.000000   0.000000   0.000000
GA7      28.361858  28.361858  28.361858  28.361858
GH8       0.000000   0.000000   0.000000   0.000000
GM7       0.000000   0.000000   0.000000   0.000000
GN7       0.000000   0.000000   0.000000   0.000000
KE8      47.440602  47.440602  47.440602  47.440602
LB7       0.000000   0.000000   0.000000   0.000000
LS8       0.000000   0.000000   0.000000   0.000000
MD7       0.000000   0.000000   0.000000   0.000000
ML8      15.485900  15.485900  15.485900  15.485900
MR7       0.000000   0.000000   0.000000   0.000000
MW7       0.000000   0.000000   0.000000   0.000000
MZ8       0.000000   0.000000   0.000000   0.000000
NG8       0.000000   0.000000   0.000000   0.000000
RW7       0.000000   0.000000   0.000000   0.000000
SL7       0.000000   0.000000   0.000000   0.000000
SN8       0.000000   0.000000   0.000000   0.000000
TZ8       0.000000   0.000000   0.000000   0.000000
UG7       0.000000   0.000000   0.000000   0.000000
ZA7      50.751703  50.751703  50.751703  50.751703
ZM7       0.000000   0.000000   0.000000   0.000000

In [178]:
# Create a new column 'Problems in Accessing Health Care'
# It will be 'big problem' if any of the specified columns have 'big problem', otherwise 'not a big problem'
df['Problem_Access'] = df[['v467b', 'v467c', 'v467d', 'v467f']].apply(
    lambda row: 'big problem' if (row == 'big problem').any() else 'not a big problem', axis=1
)

# Display the value counts of the new column to verify
display(df['Problem_Access'].value_counts())

Problem_Access
big problem          273446
not a big problem    194519
Name: count, dtype: int64

In [179]:
df.head()

,Country,v001,v005,v007,Maternal_age,highest_educational_level,Residence,sex_of_hh,v157,v158,...,History_abortion,contraceptive_use_and_intention,visited_HF_last_12months,v467b,v467c,v467d,v467f,covered_by_health_insurance,Working_status,Problem_Access
0,AO7,1,1086089,2016,38,no education,rural,male,not at all,not at all,...,yes,does not intend to use,no,not a big problem,big problem,big problem,not a big problem,no,yes,big problem
1,AO7,1,1086089,2016,40,no education,rural,male,not at all,not at all,...,no,does not intend to use,no,not a big problem,not a big problem,not a big problem,not a big problem,no,yes,not a big problem
2,AO7,1,1086089,2016,16,no education,rural,male,not at all,not at all,...,no,does not intend to use,yes,big problem,big problem,not a big problem,not a big problem,no,yes,big problem
3,AO7,1,1086089,2016,43,primary,rural,male,not at all,not at all,...,yes,does not intend to use,no,big problem,big problem,not a big problem,not a big problem,no,yes,big problem
4,AO7,1,1086089,2016,25,no education,rural,male,not at all,not at all,...,no,does not intend to use,no,not a big problem,not a big problem,not a big problem,not a big problem,no,yes,not a big problem

In [180]:
# Create a frequency table for 'v157'
v157_counts = df['v157'].value_counts()

# Display the frequency table
display(v157_counts)

v157
not at all               398088
less than once a week     41560
at least once a week      27465
almost every day            844
9.0                           0
Name: count, dtype: int64

In [ ]:
# Create a new column 'Media exposure'
# It will be 'Yes' if the woman reads a newspaper (v157), listens to the radio (v158),
# or watches TV (v159) at least once a week or almost every day. Otherwise 'No'.

# Define the conditions for 'Yes' and 'No'
yes_conditions = ['at least once a week', 'almost every day']
no_conditions = ['not at all', 'less than once a week', 'not applicable'] # Assuming 'not applicable' also means no media exposure

df['Media exposure'] = df[['v157', 'v158', 'v159']].apply(
    lambda row: 'Yes' if any(item in yes_conditions for item in row) else 'No', axis=1
)

# Display the value counts of the new column to verify
display(df['Media exposure'].value_counts())

In [ ]:
df.head()

In [ ]:
# Check for missing values in each column
missing_values = df.isnull().sum()

# Display the number of missing values for each column
display(missing_values)

In [ ]:
# Drop the specified columns
df = df.drop(columns=['v467b', 'v467c', 'v467d', 'v467f', 'v157', 'v158', 'v159'])

# Display the head of the DataFrame to confirm the columns were dropped
display(df.head())

In [ ]:
df. columns

In [ ]:
# Define the age bins and labels
age_bins = [15, 25, 35, 50]  # Upper limit is exclusive, so use 50 for 35-49
age_labels = ['15-24', '25-34', '35-49']

# Create a new column with the categorized age groups
df['Maternal_age'] = pd.cut(df['Maternal_age'], bins=age_bins, labels=age_labels, right=False) # right=False makes the intervals [a, b)

# Display the value counts of the new column to verify
display(df['Maternal_age'].value_counts())

In [ ]:
# Recategorize 'highest_educational_level' in place
educational_level_mapping = {
    'no education': 'No education',
    'primary': 'Primary Education',
    'secondary': 'Secondry education and Above',
    'higher': 'Secondry education and Above',
    '9': 'Unknown' # Assuming '9' is an unknown or missing category
}

df['highest_educational_level'] = df['highest_educational_level'].map(educational_level_mapping)

# Display the value counts of the updated column to verify
display(df['highest_educational_level'].value_counts())

In [ ]:
# Recategorize 'not a dejure resident' as 'rural' in the 'Residence' column
df['Residence'] = df['Residence'].replace('not a dejure resident', 'rural')

# Create a frequency table for 'Residence'
residence_counts = df['Residence'].value_counts()

# Display the frequency table
display(residence_counts)

In [ ]:
# Create a frequency table for 'sex_of_hh'
sex_of_hh_counts = df['sex_of_hh'].value_counts()

# Display the frequency table
display(sex_of_hh_counts)

In [ ]:
# Create a frequency table for 'owns_mobile_telephone'
owns_mobile_telephone_counts = df['owns_mobile_telephone'].value_counts()
display(owns_mobile_telephone_counts)

In [ ]:
# Recategorize 'use_of_internet'
internet_use_mapping = {
    'never': 'No',
    'yes, before last 12 months': 'No',
    'yes, last 12 months': 'Yes'
}

df['use_of_internet'] = df['use_of_internet'].map(internet_use_mapping)

# Create a frequency table for the updated 'use_of_internet' column
use_of_internet_counts = df['use_of_internet'].value_counts()
display(use_of_internet_counts)

In [ ]:
# Create a frequency table for 'Wealth_index'
Wealth_index_counts = df['Wealth_index'].value_counts()
display(Wealth_index_counts)

In [ ]:
# Create a frequency table for 'currently_pregnant'
currently_pregnant_counts = df['currently_pregnant'].value_counts()
display(currently_pregnant_counts)

In [ ]:
# Create a frequency table for 'History_abortion'
History_abortion_counts = df['History_abortion'].replace('9.0', 'no').value_counts()
display(History_abortion_counts)

In [ ]:
# Recategorize 'contraceptive_use_and_intention'
contraceptive_use_mapping = {
    'non-user - intends to use later': 'No',
    'does not intend to use': 'No',
    'never had sex': 'No',
    'using modern method': 'Yes',
    'using traditional method': 'Yes'
}

df['contraceptive_use_and_intention'] = df['contraceptive_use_and_intention'].map(contraceptive_use_mapping)

# Create a frequency table for the updated 'contraceptive_use_and_intention' column
contraceptive_use_and_intention_counts = df['contraceptive_use_and_intention'].value_counts()
display(contraceptive_use_and_intention_counts)

In [ ]:
# Create a frequency table for 'visited_HF_last_12months'
visited_HF_last_12months_counts = df['visited_HF_last_12months'].value_counts()
display(visited_HF_last_12months_counts)

In [ ]:
# Create a frequency table for 'covered_by_health_insurance'
covered_by_health_insurance_counts = df['covered_by_health_insurance'].value_counts()
display(covered_by_health_insurance_counts)

In [ ]:
# Create a frequency table for 'Working_status'
Working_status_counts = df['Working_status'].value_counts()
display(Working_status_counts)

In [ ]:
# Create a frequency table for 'Media exposure'
Media_exposure_counts = df['Media exposure'].value_counts()
display(Media_exposure_counts)

In [ ]:
df.head()

In [ ]:
# Create a frequency table for 'gave_birth_in_the_5yrs'
gave_birth_in_the_5yrs_counts = df['gave_birth_in_the_5yrs'].value_counts()

# Display the frequency table
display(gave_birth_in_the_5yrs_counts)

In [ ]:
# Recategorize 'gave_birth_in_the_5yrs'
birth_mapping = {
    'no births': 'No',
    '1.0': 'Yes',
    '2.0': 'Yes',
    '3.0': 'Yes',
    '4.0': 'Yes',
    '5.0': 'Yes',
    '6.0': 'Yes',
    '7.0': 'Yes'
}

df['gave_birth_in_the_5yrs'] = df['gave_birth_in_the_5yrs'].map(birth_mapping)

# Create a frequency table for the updated 'gave_birth_in_the_5yrs' column
gave_birth_in_the_5yrs_counts = df['gave_birth_in_the_5yrs'].value_counts()
display(gave_birth_in_the_5yrs_counts)

In [ ]:
# Create a frequency table for 'gave_birth_in_the_5yrs'
gave_birth_in_the_5yrs_counts = df['gave_birth_in_the_5yrs'].value_counts()

# Display the frequency table
display(gave_birth_in_the_5yrs_counts)